### ISSUE TITLE
Define properties to search through

### ISSUE THREAD

**Issue by PantherX99** [Mihaiii/semantic-autocomplete#3]
Currently, i use a custom filterOptions function for my Autocomplete component, in which i provide the names of the keys to define the properties to search. Some properties are necessary for the onChange event and renderOption function but should not be used for search.
Is a similar behaviour achievable?

**Comment by Mihaiii** [comment]
Can't this issue be solved by setting [getOptionLabel](https://mui.com/material-ui/api/autocomplete/#autocomplete-prop-getOptionLabel) instead of setting `filterOptions`?

If not, please provide an example.

`filterOptions` should be used to determine the filtering strategy and this whole component is about one single strategy (filter/sort using embeddings).

**Comment by Mihaiii** [comment]
Closing as answered.
Please reopen if needed.
